# Generated by Django 5.1.1 on 2024-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_data_id_user_data_user_id_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='amount',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
