# Generated by Django 5.1.1 on 2024-10-20 13:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_preferences_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='is_constant',
            field=models.BooleanField(default=False),
        )
    ]
