# Generated by Django 5.1.1 on 2024-10-26 09:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_preferences_is_constant_user_data_is_staff_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        )
    ]
