# Generated by Django 5.1.1 on 2024-11-05 14:05

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_data_is_staff_user_data_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='expenses',
            field=models.PositiveIntegerField(default=0),
        )
    ]
